/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfirm: typeof import('./components/common/AppConfirm.vue')['default']
    AppToast: typeof import('./components/common/AppToast.vue')['default']
    ChessBoard: typeof import('./components/chess/ChessBoard.vue')['default']
    ChessPiece: typeof import('./components/chess/ChessPiece.vue')['default']
    GameControls: typeof import('./components/game/GameControls.vue')['default']
    GameTimer: typeof import('./components/game/GameTimer.vue')['default']
    MoveList: typeof import('./components/chess/MoveList.vue')['default']
    PlaybackControls: typeof import('./components/game/PlaybackControls.vue')['default']
    PlayerInfo: typeof import('./components/game/PlayerInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
